name: Generate Podcast Feed
on: [push]
# Whenever someone pushes something into out branch, such as a new audio file or adding something new in the feed.yaml file
# We need to generate a new podcast.xml file then
# In order to do this, we have to choose a command which upon getting this whole process will be initiated
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: TheMarvelFan/podcast-generator@main
