name: Generate Podcast Feed
on: [push]
# Whenever someone pushes something into out branch, such as a new audio file or adding something new in the feed.yaml file
# We need to generate a new podcast.xml file then
# In order to do this, we have to choose a command which upon getting this whole process will be initiated
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3
        # Can have different releases
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run Feed Generator
        run: python feed.py
      - name: Push Repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@gmail.com
          git add .
          git commit -m "modified the feed"
          git push
